import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "../components/header";
import { AnimalProvider } from "@/contexts/animalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Farm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="emerald">
      <body className={inter.className}>
        <AnimalProvider>
          <Header/>
          {children}
        </AnimalProvider>
      </body>
    </html>
  );
}