import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./components/header";
import { AnimalProvider } from "@/contexts/animalContext";
import { FazendaProvider } from "@/contexts/farmContexts";
import { ProducaoProvider } from "@/contexts/production";
import { FazendeiroProvider } from "@/contexts/farmerContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Farm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="emerald">
      <body className={inter.className}>
        <ProducaoProvider>
          <FazendeiroProvider>
            <FazendaProvider>
              <AnimalProvider>
                <Header />
                {children}
              </AnimalProvider>
            </FazendaProvider>
          </FazendeiroProvider>
        </ProducaoProvider>
      </body>
    </html>
  );
}
